// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

import 'todo.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'todos.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'todos.g.dart';

@freezed
class Todos with _$Todos {
  const factory Todos({
    @Default([]) List<Todo> values,
  }) = _Todos;
  const Todos._();
  List<Todo> get completed {
    return values.where((todo) => todo.completed).toList();
  }

  List<Todo> get active {
    return values.where((todo) => !todo.completed).toList();
  }

  factory Todos.fromJson(Map<String, Object?> json) => _$TodosFromJson(json);
}
